version: '2.0'
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
    - "80:8080"
    volumes:
    - ./swagger:/foo
    environment:
    - SWAGGER_JSON=/foo/swagger.json
    - SUPPORTED_SUBMIT_METHODS="[\"get\", \"post\"]"
